---
name: Simulate High Traffic

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        node: [0, 1, 2, 3, 4, 5, 6, 7]
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ matrix.node }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*
      - run: corepack enable && pnpm --version
      - run: pnpm install --loglevel=error
      - run: node -r esbuild-register src/action.ts
        working-directory: apps/studio
        env:
          MINUTES: 15
          BATCH: 10
          SANITY_API_WRITE_TOKEN: ${{ secrets.SANITY_API_WRITE_TOKEN }}
